# Generated by Django 5.2.16 on 2026-09-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0032_plexaccount_section_settings'),
        ('integrations', '0035_alter_koreaderaccount_finished_threshold'),
    ]

    operations = [
    ]
