# Generated by Django 5.2.16 on 2026-09-05 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0176_move_hardcover_user_key"),
        ("users", "0129_alter_user_anime_metadata_source_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="hardcover_api_key",
        ),
    ]
